# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7472cbbbcc11d04502e9d7083a248ffcabfb048f1fb69bb893aa43671d6a46dc7c7efeb750750ce0217fdcc80705f530b33d122fef6aa6dc352ec5d298caf65d

test:
  secret_key_base: 3ff5e202e0f9958d464563054ddddf880dd41a6becd657a80237553779ed897b1a6dce98eeac7e23511b03697f46668ee68dfd1a0993f5703b56a827fbb5224c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
